// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue` namespace.
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-bluecatbird")))]
#[cfg(feature = "namespace-bluecatbird")]
pub mod catbird;
