// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.message.defs` namespace.
//!Definitions for encrypted MLS message payload structure. The ciphertext bytes in messageView decrypt to the payloadView structure defined here. NOTE: Since payloads are end-to-end encrypted, client implementations may use simplified JSON encodings (e.g., without $type fields) as the server never sees the plaintext.
///Admin action notification (E2EE). Sent alongside server API calls to inform all clients.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AdminActionData {
    ///Type of admin action performed
    pub action: String,
    ///Optional reason for the action
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reason: core::option::Option<String>,
    ///DID of member being acted upon
    pub target_did: crate::types::string::Did,
    ///When the action was performed
    pub timestamp: crate::types::string::Datetime,
}
pub type AdminAction = crate::types::Object<AdminActionData>;
///Encrypted admin roster distributed via MLS application messages. Clients verify admin actions against this roster.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AdminRosterData {
    ///List of admin DIDs for this conversation
    pub admins: Vec<crate::types::string::Did>,
    ///SHA-256 hash of (version || admins) for integrity verification
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub hash: core::option::Option<String>,
    ///Monotonic roster version number (increments on each change)
    pub version: core::num::NonZeroU64,
}
pub type AdminRoster = crate::types::Object<AdminRosterData>;
///Tenor GIF embed (converted to MP4 for efficient playback)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct GifEmbedData {
    ///GIF/video height in pixels
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub height: core::option::Option<core::num::NonZeroU64>,
    ///MP4 video URL for efficient playback
    pub mp4_url: String,
    ///Original Tenor GIF URL (e.g., https://tenor.com/view/...)
    pub tenor_url: String,
    ///Thumbnail image URL for preview
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub thumbnail_url: core::option::Option<String>,
    ///GIF title or description from Tenor
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub title: core::option::Option<String>,
    ///GIF/video width in pixels
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub width: core::option::Option<core::num::NonZeroU64>,
}
pub type GifEmbed = crate::types::Object<GifEmbedData>;
///External link preview with metadata
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct LinkEmbedData {
    ///Page description from Open Graph or meta tags
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Canonical domain (e.g., 'bsky.app', 'github.com')
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub domain: core::option::Option<String>,
    ///Thumbnail/preview image URL
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub thumbnail_url: core::option::Option<String>,
    ///Page title from Open Graph or meta tags
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub title: core::option::Option<String>,
    ///Full URL of the external link
    pub url: String,
}
pub type LinkEmbed = crate::types::Object<LinkEmbedData>;
///Decrypted message payload structure (what's inside the encrypted ciphertext). This is what clients decrypt from the ciphertext bytes.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PayloadViewData {
    ///Admin action notification (for messageType: adminAction)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub admin_action: core::option::Option<AdminAction>,
    ///Admin roster update (for messageType: adminRoster)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub admin_roster: core::option::Option<AdminRoster>,
    ///Optional rich media embed (record, link, or GIF). Clients can add new types in future versions.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub embed: core::option::Option<crate::types::Union<PayloadViewEmbedRefs>>,
    ///Message type discriminator: text (default), adminRoster, adminAction
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub message_type: core::option::Option<String>,
    ///Message text content (for messageType: text)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub text: core::option::Option<String>,
    ///Payload format version for future compatibility. Current version is 1.
    pub version: i64,
}
pub type PayloadView = crate::types::Object<PayloadViewData>;
///Bluesky record embed (quote post). References an AT Protocol record by URI.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordEmbedData {
    ///DID of the record author
    pub author_did: crate::types::string::Did,
    ///CID of the record for verification
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cid: core::option::Option<crate::types::string::Cid>,
    ///Timestamp when the record was created
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<crate::types::string::Datetime>,
    ///Preview text (first line or excerpt) from the record
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub preview_text: core::option::Option<String>,
    ///AT-URI of the referenced record (e.g., at://did:plc:xyz/app.bsky.feed.post/abc123)
    pub uri: String,
}
pub type RecordEmbed = crate::types::Object<RecordEmbedData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum PayloadViewEmbedRefs {
    #[serde(rename = "blue.catbird.mls.message.defs#recordEmbed")]
    RecordEmbed(Box<RecordEmbed>),
    #[serde(rename = "blue.catbird.mls.message.defs#linkEmbed")]
    LinkEmbed(Box<LinkEmbed>),
    #[serde(rename = "blue.catbird.mls.message.defs#gifEmbed")]
    GifEmbed(Box<GifEmbed>),
}
