// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.addMembers` namespace.
//!Add new members to an existing MLS conversation
pub const NSID: &str = "blue.catbird.mls.addMembers";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Conversation identifier
    pub convo_id: String,
    ///DIDs of members to add
    pub members: Vec<crate::types::string::Did>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Base64-encoded MLS Commit message for existing members
    pub commit: String,
    ///Updated conversation view
    pub convo: crate::blue::catbird::mls::defs::ConvoView,
    ///Welcome messages for new members
    pub welcome_messages: Vec<WelcomeMessage>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of the conversation
    NotMember(Option<String>),
    ///Key package not found for one or more members
    KeyPackageNotFound(Option<String>),
    ///One or more DIDs are already members
    AlreadyMember(Option<String>),
    ///Would exceed maximum member count
    TooManyMembers(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageNotFound(msg) => {
                write!(_f, "KeyPackageNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::AlreadyMember(msg) => {
                write!(_f, "AlreadyMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::TooManyMembers(msg) => {
                write!(_f, "TooManyMembers")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct WelcomeMessageData {
    ///DID of the new member
    pub did: crate::types::string::Did,
    ///Base64-encoded MLS Welcome message for this member
    pub welcome: String,
}
pub type WelcomeMessage = crate::types::Object<WelcomeMessageData>;
