// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.createConvo` namespace.
//!Create a new MLS conversation with optional initial members and metadata
pub const NSID: &str = "blue.catbird.mls.createConvo";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///MLS cipher suite to use for this conversation
    pub cipher_suite: String,
    ///DIDs of initial members to add to the conversation
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub initial_members: core::option::Option<Vec<crate::types::string::Did>>,
    ///Optional conversation metadata (name, description, avatar)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub metadata: core::option::Option<MetadataInput>,
}
pub type Input = crate::types::Object<InputData>;
pub type Output = crate::blue::catbird::mls::defs::ConvoView;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///The specified cipher suite is not supported
    InvalidCipherSuite(Option<String>),
    ///Key package not found for one or more initial members
    KeyPackageNotFound(Option<String>),
    ///Too many initial members specified (max 100)
    TooManyMembers(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidCipherSuite(msg) => {
                write!(_f, "InvalidCipherSuite")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageNotFound(msg) => {
                write!(_f, "KeyPackageNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::TooManyMembers(msg) => {
                write!(_f, "TooManyMembers")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
///Input metadata for conversation creation
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MetadataInputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<crate::types::BlobRef>,
    ///Conversation description
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Conversation display name
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub name: core::option::Option<String>,
}
pub type MetadataInput = crate::types::Object<MetadataInputData>;
