// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.defs` namespace.
//!Shared type definitions for MLS (Message Layer Security) protocol
///Reference to a blob (file attachment)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BlobRefData {
    ///Content identifier (CID)
    pub cid: String,
    ///MIME type of the blob
    pub mime_type: String,
    ///AT URI reference to blob
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub r#ref: core::option::Option<String>,
    ///Blob size in bytes (max 50MB)
    pub size: crate::types::LimitedU32<52428800u32>,
}
pub type BlobRef = crate::types::Object<BlobRefData>;
///Metadata for a conversation (name, description, avatar)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ConvoMetadataData {
    ///Conversation avatar image
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<crate::types::BlobRef>,
    ///Conversation description
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///Conversation display name
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub name: core::option::Option<String>,
}
pub type ConvoMetadata = crate::types::Object<ConvoMetadataData>;
///View of an MLS conversation with member and epoch information
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ConvoViewData {
    ///MLS cipher suite used for this conversation
    pub cipher_suite: String,
    ///Conversation creation timestamp
    pub created_at: crate::types::string::Datetime,
    ///DID of the conversation creator
    pub creator: crate::types::string::Did,
    ///Current MLS epoch number
    pub epoch: usize,
    ///MLS group identifier (hex-encoded)
    pub group_id: String,
    ///Conversation identifier (TID)
    pub id: String,
    ///Timestamp of last message
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub last_message_at: core::option::Option<crate::types::string::Datetime>,
    ///Current conversation members
    pub members: Vec<MemberView>,
    ///Optional conversation metadata
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub metadata: core::option::Option<ConvoMetadata>,
}
pub type ConvoView = crate::types::Object<ConvoViewData>;
///Pointer to ciphertext stored in an external provider
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ExternalAssetData {
    ///MIME type of the ciphertext payload
    pub mime_type: String,
    ///Storage provider identifier
    pub provider: String,
    ///SHA-256 of ciphertext payload bytes
    #[serde(with = "serde_bytes")]
    pub sha256: Vec<u8>,
    ///Size in bytes of the ciphertext payload
    pub size: usize,
    ///Provider-specific URI (e.g., cloudkit://..., firestore://..., gdrive://...)
    pub uri: String,
}
pub type ExternalAsset = crate::types::Object<ExternalAssetData>;
///Reference to an MLS key package for adding members
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct KeyPackageRefData {
    ///Supported cipher suite for this key package
    pub cipher_suite: String,
    ///Key package creation time
    pub created_at: crate::types::string::Datetime,
    ///Owner DID
    pub did: crate::types::string::Did,
    ///Key package expiration time
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub expires_at: core::option::Option<crate::types::string::Datetime>,
    ///Key package identifier
    pub id: String,
    ///MLS key package bytes
    #[serde(with = "serde_bytes")]
    pub key_package: Vec<u8>,
}
pub type KeyPackageRef = crate::types::Object<KeyPackageRefData>;
///View of a conversation member with MLS credentials
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MemberViewData {
    ///MLS credential bytes
    #[serde(default)]
    #[serde(with = "serde_bytes")]
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub credential: core::option::Option<Vec<u8>>,
    ///Member DID
    pub did: crate::types::string::Did,
    ///When member joined the conversation
    pub joined_at: crate::types::string::Datetime,
    ///MLS leaf index in tree structure
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub leaf_index: core::option::Option<usize>,
}
pub type MemberView = crate::types::Object<MemberViewData>;
///View of an encrypted MLS message
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MessageViewData {
    ///Attachment ciphertext payload pointers
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub attachments: core::option::Option<Vec<ExternalAsset>>,
    ///MIME type of decrypted content
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub content_type: core::option::Option<String>,
    ///Conversation identifier
    pub convo_id: String,
    ///Message creation timestamp
    pub created_at: crate::types::string::Datetime,
    ///MLS epoch when message was sent
    pub epoch: usize,
    ///Message identifier (TID)
    pub id: String,
    ///Pointer to the message ciphertext payload
    pub payload: ExternalAsset,
    ///If this message is a reply, AT-URI of the message being replied to
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reply_uri: core::option::Option<String>,
    ///DID of message sender
    pub sender: crate::types::string::Did,
}
pub type MessageView = crate::types::Object<MessageViewData>;
