// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.publishKeyPackage` namespace.
pub const NSID: &str = "blue.catbird.mls.publishKeyPackage";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Cipher suite of the key package
    pub cipher_suite: String,
    ///Optional expiration timestamp (defaults to 30 days)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub expires_at: core::option::Option<crate::types::string::Datetime>,
    ///Base64-encoded MLS key package
    pub key_package: String,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Published key package reference
    pub key_package: crate::blue::catbird::mls::defs::KeyPackageRef,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Key package is malformed or invalid
    InvalidKeyPackage(Option<String>),
    ///Cipher suite is not supported
    InvalidCipherSuite(Option<String>),
    ///Expiration date is too far in the future (max 90 days)
    ExpirationTooFar(Option<String>),
    ///Maximum number of key packages per user exceeded
    TooManyKeyPackages(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidKeyPackage(msg) => {
                write!(_f, "InvalidKeyPackage")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidCipherSuite(msg) => {
                write!(_f, "InvalidCipherSuite")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::ExpirationTooFar(msg) => {
                write!(_f, "ExpirationTooFar")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::TooManyKeyPackages(msg) => {
                write!(_f, "TooManyKeyPackages")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
