// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.sendMessage` namespace.
pub const NSID: &str = "blue.catbird.mls.sendMessage";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Attachment ciphertext payload pointers
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub attachments: core::option::Option<
        Vec<crate::blue::catbird::mls::defs::ExternalAsset>,
    >,
    ///MIME type of the plaintext content
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub content_type: core::option::Option<String>,
    ///Conversation identifier
    pub convo_id: String,
    ///Pointer to the message ciphertext payload
    pub payload: crate::blue::catbird::mls::defs::ExternalAsset,
    ///If reply, AT-URI of the message being replied to
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reply_uri: core::option::Option<String>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Created message view
    pub message: crate::blue::catbird::mls::defs::MessageView,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of the conversation
    NotMember(Option<String>),
    ///Payload or attachment pointer is invalid
    InvalidAsset(Option<String>),
    ///Message epoch does not match current conversation epoch
    EpochMismatch(Option<String>),
    ///Message exceeds maximum size policy
    MessageTooLarge(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidAsset(msg) => {
                write!(_f, "InvalidAsset")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::EpochMismatch(msg) => {
                write!(_f, "EpochMismatch")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::MessageTooLarge(msg) => {
                write!(_f, "MessageTooLarge")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
