// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.uploadBlob` namespace.
//!Upload a blob (file attachment) for use in MLS conversations and messages
pub const NSID: &str = "blue.catbird.mls.uploadBlob";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    pub blob: crate::types::BlobRef,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Blob exceeds maximum size of 50MB
    BlobTooLarge(Option<String>),
    ///User storage quota exceeded
    QuotaExceeded(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::BlobTooLarge(msg) => {
                write!(_f, "BlobTooLarge")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::QuotaExceeded(msg) => {
                write!(_f, "QuotaExceeded")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
