// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.addMembers` namespace.
//!Add new members to an existing MLS conversation
pub const NSID: &str = "blue.catbird.mls.addMembers";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Optional base64url-encoded MLS Commit message
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub commit: core::option::Option<String>,
    ///Conversation identifier
    pub convo_id: String,
    ///DIDs of members to add
    pub did_list: Vec<crate::types::string::Did>,
    ///Client-generated UUID for idempotent request retries. Optional but recommended.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub idempotency_key: core::option::Option<String>,
    ///Array of {did, hash} objects mapping each new member to their key package hash. Required for multi-device support.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub key_package_hashes: core::option::Option<Vec<KeyPackageHashEntry>>,
    ///Base64url-encoded MLS Welcome message containing encrypted secrets for ALL new members
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub welcome_message: core::option::Option<String>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///New epoch number after adding members
    pub new_epoch: usize,
    ///Whether the operation succeeded
    pub success: bool,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of the conversation
    NotMember(Option<String>),
    ///Key package not found for one or more members
    KeyPackageNotFound(Option<String>),
    ///One or more DIDs are already members
    AlreadyMember(Option<String>),
    ///Would exceed maximum member count
    TooManyMembers(Option<String>),
    ///Cannot add user who has blocked or been blocked by an existing member (Bluesky social graph enforcement)
    BlockedByMember(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageNotFound(msg) => {
                write!(_f, "KeyPackageNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::AlreadyMember(msg) => {
                write!(_f, "AlreadyMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::TooManyMembers(msg) => {
                write!(_f, "TooManyMembers")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::BlockedByMember(msg) => {
                write!(_f, "BlockedByMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
///Maps a DID to the key package hash used for their Welcome message
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct KeyPackageHashEntryData {
    ///DID of the member
    pub did: crate::types::string::Did,
    ///Hex-encoded SHA-256 hash of the key package used
    pub hash: String,
}
pub type KeyPackageHashEntry = crate::types::Object<KeyPackageHashEntryData>;
