// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.checkBlocks` namespace.
//!Check Bluesky block relationships between users for MLS conversation moderation
pub const NSID: &str = "blue.catbird.mls.checkBlocks";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///DIDs to check for mutual blocks (2-100 users)
    pub dids: Vec<crate::types::string::Did>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///List of block relationships between the provided DIDs
    pub blocks: Vec<BlockRelationship>,
    ///When the block status was checked (for cache invalidation)
    pub checked_at: crate::types::string::Datetime,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Too many DIDs provided (max 100)
    TooManyDids(Option<String>),
    ///Could not reach Bluesky service to check blocks
    BlueskyServiceUnavailable(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::TooManyDids(msg) => {
                write!(_f, "TooManyDids")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::BlueskyServiceUnavailable(msg) => {
                write!(_f, "BlueskyServiceUnavailable")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
///Represents a block relationship between two users on Bluesky
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BlockRelationshipData {
    ///AT-URI of the block record on Bluesky (for verification)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub block_uri: core::option::Option<String>,
    ///DID of user who was blocked
    pub blocked_did: crate::types::string::Did,
    ///DID of user who created the block
    pub blocker_did: crate::types::string::Did,
    ///When the block was created on Bluesky
    pub created_at: crate::types::string::Datetime,
}
pub type BlockRelationship = crate::types::Object<BlockRelationshipData>;
