// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.getAdminStats` namespace.
//!Get moderation statistics for App Store compliance demonstration
pub const NSID: &str = "blue.catbird.mls.getAdminStats";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Optional: Get stats for specific conversation (requires admin). Omit for global stats (requires superadmin).
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub convo_id: core::option::Option<String>,
    ///Optional: Only include stats since this timestamp
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub since: core::option::Option<crate::types::string::Datetime>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Conversation ID if stats are for a specific conversation
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub convo_id: core::option::Option<String>,
    ///When these statistics were generated
    pub generated_at: crate::types::string::Datetime,
    pub stats: ModerationStats,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///User is not authorized to view moderation statistics
    NotAuthorized(Option<String>),
    ///Conversation not found (when convoId is specified)
    ConvoNotFound(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::NotAuthorized(msg) => {
                write!(_f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
///Aggregate moderation statistics
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ModerationStatsData {
    ///Average time to resolve reports (in hours)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub average_resolution_time_hours: core::option::Option<usize>,
    ///Number of Bluesky block conflicts resolved by admins
    pub block_conflicts_resolved: usize,
    ///Number of reports awaiting admin review
    pub pending_reports: usize,
    ///Breakdown of reports by category
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reports_by_category: core::option::Option<ReportCategoryCounts>,
    ///Number of reports resolved by admins
    pub resolved_reports: usize,
    ///Total number of members removed by admins
    pub total_removals: usize,
    ///Total number of member reports submitted
    pub total_reports: usize,
}
pub type ModerationStats = crate::types::Object<ModerationStatsData>;
///Count of reports by category
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ReportCategoryCountsData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub harassment: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub hate_speech: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub impersonation: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub other_category: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub privacy_violation: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub sexual_content: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub spam: core::option::Option<usize>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub violence: core::option::Option<usize>,
}
pub type ReportCategoryCounts = crate::types::Object<ReportCategoryCountsData>;
