// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.getWelcome` namespace.
//!Get Welcome message for joining an MLS conversation
pub const NSID: &str = "blue.catbird.mls.getWelcome";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Conversation identifier
    pub convo_id: String,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Conversation identifier
    pub convo_id: String,
    ///Base64url-encoded MLS Welcome message data
    pub welcome: String,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of the conversation
    NotMember(Option<String>),
    ///No Welcome message available for this user
    WelcomeNotFound(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::WelcomeNotFound(msg) => {
                write!(_f, "WelcomeNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
