// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.getKeyPackages` namespace.
pub const NSID: &str = "blue.catbird.mls.getKeyPackages";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter by cipher suite
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cipher_suite: core::option::Option<String>,
    ///DIDs to fetch key packages for
    pub dids: Vec<crate::types::string::Did>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Available key packages for the requested DIDs
    pub key_packages: Vec<crate::blue::catbird::mls::defs::KeyPackageRef>,
    ///DIDs for which no key packages were found
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub missing: core::option::Option<Vec<crate::types::string::Did>>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Too many DIDs requested
    TooManyDids(Option<String>),
    ///One or more DIDs are invalid
    InvalidDid(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::TooManyDids(msg) => {
                write!(_f, "TooManyDids")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidDid(msg) => {
                write!(_f, "InvalidDid")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
