// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.getBlockStatus` namespace.
//!Get block relationships relevant to a specific conversation
pub const NSID: &str = "blue.catbird.mls.getBlockStatus";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Conversation identifier
    pub convo_id: String,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///List of block relationships between conversation members
    pub blocks: Vec<crate::blue::catbird::mls::check_blocks::BlockRelationship>,
    ///When the block status was checked
    pub checked_at: crate::types::string::Datetime,
    ///Conversation identifier
    pub convo_id: String,
    ///True if any members have blocked each other
    pub has_conflicts: bool,
    ///Total number of members checked
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub member_count: core::option::Option<usize>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of this conversation
    NotMember(Option<String>),
    ///Only admins can check block status
    NotAdmin(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotAdmin(msg) => {
                write!(_f, "NotAdmin")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
