// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.getExpectedConversations` namespace.
//!Get list of conversations the user should be a member of but may be missing locally
pub const NSID: &str = "blue.catbird.mls.getExpectedConversations";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Optional device ID to check. Defaults to current device from auth token
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub device_id: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///List of conversations the user should be in
    pub conversations: Vec<ExpectedConversation>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Authentication required
    Unauthorized(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::Unauthorized(msg) => {
                write!(_f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ExpectedConversationData {
    ///Conversation identifier
    pub convo_id: String,
    ///Whether the specific device is currently in the MLS group
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub device_in_group: core::option::Option<bool>,
    ///Timestamp of last activity in conversation
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub last_activity: core::option::Option<crate::types::string::Datetime>,
    ///Number of active members in conversation
    pub member_count: i64,
    ///Conversation name
    pub name: String,
    ///Whether user has an active rejoin request for this conversation
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub needs_rejoin: core::option::Option<bool>,
    ///Whether this device should be in the MLS group
    pub should_be_in_group: bool,
}
pub type ExpectedConversation = crate::types::Object<ExpectedConversationData>;
