// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.listDevices` namespace.
pub const NSID: &str = "blue.catbird.mls.listDevices";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///List of user's registered devices, ordered by last seen (most recent first)
    pub devices: Vec<DeviceInfo>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DeviceInfoData {
    ///Full device credential DID (did:plc:user#device-uuid)
    pub credential_did: String,
    ///Server-generated device ID (UUID)
    pub device_id: String,
    ///Human-readable device name (e.g., 'Josh's iPhone')
    pub device_name: String,
    ///Persistent device UUID (if provided during registration)
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub device_uuid: core::option::Option<String>,
    ///Number of available (unconsumed) key packages for this device
    pub key_package_count: usize,
    ///Timestamp of last device activity
    pub last_seen_at: crate::types::string::Datetime,
    ///Timestamp when device was first registered
    pub registered_at: crate::types::string::Datetime,
}
pub type DeviceInfo = crate::types::Object<DeviceInfoData>;
