// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.registerDevice` namespace.
pub const NSID: &str = "blue.catbird.mls.registerDevice";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///App version string
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub app_version: core::option::Option<String>,
    ///Unique device identifier (UUID). Client-generated and persisted across app launches.
    pub device_id: String,
    ///Human-readable device name (e.g., 'Josh's iPhone', 'MacBook Pro')
    pub device_name: String,
    ///Device platform
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub platform: core::option::Option<String>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Full device credential DID (did:plc:user#device-uuid). Use this as the MLS credential identity.
    pub credential_did: String,
    ///Confirmed device ID
    pub device_id: String,
    ///True if this is a new registration, false if updating existing device
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub is_new_device: core::option::Option<bool>,
    ///When the device was registered
    pub registered_at: crate::types::string::Datetime,
    ///Base user DID without device suffix
    pub user_did: String,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    InvalidDeviceId(Option<String>),
    InvalidDeviceName(Option<String>),
    DeviceAlreadyRegistered(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidDeviceId(msg) => {
                write!(_f, "InvalidDeviceId")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidDeviceName(msg) => {
                write!(_f, "InvalidDeviceName")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::DeviceAlreadyRegistered(msg) => {
                write!(_f, "DeviceAlreadyRegistered")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
