// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.requestRejoin` namespace.
//!Request to rejoin an MLS conversation after local state loss
pub const NSID: &str = "blue.catbird.mls.requestRejoin";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Conversation identifier to rejoin
    pub convo_id: String,
    ///Base64url-encoded fresh MLS KeyPackage for re-adding to the group
    pub key_package: String,
    ///Optional reason for rejoin request
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reason: core::option::Option<String>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Timestamp if request was auto-approved
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub approved_at: core::option::Option<crate::types::string::Datetime>,
    ///Whether request is pending approval (true) or auto-approved (false)
    pub pending: bool,
    ///Rejoin request identifier for tracking
    pub request_id: String,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found or user was never a member
    ConvoNotFound(Option<String>),
    ///User is already an active member with valid group state
    AlreadyMember(Option<String>),
    ///KeyPackage is malformed, expired, or invalid
    InvalidKeyPackage(Option<String>),
    ///Too many rejoin requests in short period
    RateLimitExceeded(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::AlreadyMember(msg) => {
                write!(_f, "AlreadyMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidKeyPackage(msg) => {
                write!(_f, "InvalidKeyPackage")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::RateLimitExceeded(msg) => {
                write!(_f, "RateLimitExceeded")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
