// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.resolveReport` namespace.
//!Resolve a report with an action (admin-only)
pub const NSID: &str = "blue.catbird.mls.resolveReport";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///Action taken in response to report
    pub action: String,
    ///Optional internal notes about resolution
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub notes: core::option::Option<String>,
    ///Report identifier to resolve
    pub report_id: String,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Whether resolution succeeded
    pub ok: bool,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Caller is not an admin
    NotAdmin(Option<String>),
    ///Report does not exist
    ReportNotFound(Option<String>),
    ///Report was already resolved
    AlreadyResolved(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::NotAdmin(msg) => {
                write!(_f, "NotAdmin")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::ReportNotFound(msg) => {
                write!(_f, "ReportNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::AlreadyResolved(msg) => {
                write!(_f, "AlreadyResolved")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
