// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.sendMessage` namespace.
pub const NSID: &str = "blue.catbird.mls.sendMessage";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///MLS encrypted message ciphertext bytes (MUST be padded to paddedSize)
    #[serde(with = "serde_bytes")]
    pub ciphertext: Vec<u8>,
    ///Conversation identifier
    pub convo_id: String,
    ///Original plaintext size before padding (for metadata privacy)
    pub declared_size: crate::types::LimitedU32<10485760u32>,
    ///MLS epoch number when message was encrypted
    pub epoch: usize,
    ///Deprecated: Use msgId instead. Client-generated UUID for idempotent request retries.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub idempotency_key: core::option::Option<String>,
    ///Client-generated ULID for message deduplication. MUST be included in MLS message AAD.
    pub msg_id: String,
    ///Padded ciphertext size in bytes. Must be 512, 1024, 2048, 4096, 8192, or multiples of 8192 up to 10MB.
    pub padded_size: crate::types::BoundedU32<512u32, 10485760u32>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Created message identifier
    pub message_id: String,
    ///Server timestamp when message was received
    pub received_at: crate::types::string::Datetime,
    ///Verified sender DID from JWT (server-provided, never trust client)
    pub sender: crate::types::string::Did,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Conversation not found
    ConvoNotFound(Option<String>),
    ///Caller is not a member of the conversation
    NotMember(Option<String>),
    ///Payload or attachment pointer is invalid
    InvalidAsset(Option<String>),
    ///Message epoch does not match current conversation epoch
    EpochMismatch(Option<String>),
    ///Message exceeds maximum size policy
    MessageTooLarge(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConvoNotFound(msg) => {
                write!(_f, "ConvoNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::NotMember(msg) => {
                write!(_f, "NotMember")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::InvalidAsset(msg) => {
                write!(_f, "InvalidAsset")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::EpochMismatch(msg) => {
                write!(_f, "EpochMismatch")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::MessageTooLarge(msg) => {
                write!(_f, "MessageTooLarge")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
