// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.validateDeviceState` namespace.
pub const NSID: &str = "blue.catbird.mls.validateDeviceState";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Optional device ID to validate; defaults to current device
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub device_id: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Number of conversations device is actually member of
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub actual_convos: core::option::Option<i64>,
    ///Number of conversations device should be member of
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub expected_convos: core::option::Option<i64>,
    ///Overall validation status
    pub is_valid: bool,
    ///List of detected issues
    pub issues: Vec<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub key_package_inventory: core::option::Option<KeyPackageInventory>,
    ///List of conversation IDs with pending rejoin requests
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub pending_rejoin_requests: core::option::Option<Vec<String>>,
    ///Actionable recommendations to fix issues
    pub recommendations: Vec<String>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct KeyPackageInventoryData {
    ///Number of available key packages
    pub available: i64,
    ///Whether more key packages need to be uploaded
    pub needs_replenishment: bool,
    ///Key packages available per device
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub per_device_count: core::option::Option<i64>,
    ///Target threshold for key packages
    pub target: i64,
}
pub type KeyPackageInventory = crate::types::Object<KeyPackageInventoryData>;
