// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `blue.catbird.mls.validateWelcome` namespace.
pub const NSID: &str = "blue.catbird.mls.validateWelcome";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct InputData {
    ///MLS Welcome message bytes to validate
    #[serde(with = "serde_bytes")]
    pub welcome_message: Vec<u8>,
}
pub type Input = crate::types::Object<InputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///MLS group identifier (hex-encoded) extracted from Welcome message
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub group_id: core::option::Option<String>,
    ///SHA256 hex hash of the key package referenced in the Welcome message
    pub key_package_hash: String,
    ///DID of the recipient (authenticated user). Confirms Welcome is for this user.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub recipient_did: core::option::Option<crate::types::string::Did>,
    ///Whether the key package was successfully reserved. If true, client should process Welcome within 5 minutes.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reserved: core::option::Option<bool>,
    ///Timestamp when reservation expires (5 minutes from now). Only present if reserved is true.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reserved_until: core::option::Option<crate::types::string::Datetime>,
    ///Whether the Welcome message is valid and key package is available
    pub valid: bool,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    ///Welcome message is malformed or cannot be parsed
    InvalidWelcome(Option<String>),
    ///Referenced key package was never uploaded by this user
    KeyPackageNotFound(Option<String>),
    ///Referenced key package has already been used
    KeyPackageAlreadyConsumed(Option<String>),
    ///Referenced key package is reserved by another Welcome message
    KeyPackageReserved(Option<String>),
    ///Welcome message is not for the authenticated user
    RecipientMismatch(Option<String>),
}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::InvalidWelcome(msg) => {
                write!(_f, "InvalidWelcome")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageNotFound(msg) => {
                write!(_f, "KeyPackageNotFound")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageAlreadyConsumed(msg) => {
                write!(_f, "KeyPackageAlreadyConsumed")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::KeyPackageReserved(msg) => {
                write!(_f, "KeyPackageReserved")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
            Error::RecipientMismatch(msg) => {
                write!(_f, "RecipientMismatch")?;
                if let Some(msg) = msg {
                    write!(_f, ": {msg}")?;
                }
            }
        }
        Ok(())
    }
}
