pub mod actors;
pub mod auth;
pub mod crypto;
pub mod db;
pub mod fanout;
pub mod handlers;
pub mod health;
// pub mod jobs;  // Temporarily disabled - requires new DB schema
pub mod metrics;
pub mod middleware;
pub mod models;
pub mod realtime;
pub mod storage;
pub mod util;

// Re-export atrium-api types so generated modules compile
pub use atrium_api::types;

// Generated types from lexicon schemas (generated by atrium-codegen)
pub mod generated;
pub mod generated_types;

// Re-export generated namespace at crate root for generated code's internal references
pub use generated::blue;

// sqlx trait implementations for Atrium types
pub mod sqlx_atrium;
